spring.datasource.url: jdbc:postgresql://localhost:5432/ads
spring.datasource.username: ads
spring.datasource.password: admin
spring.data.web.pageable.max-page-size: 1000

springdoc.api-docs.enabled: false
springdoc.swagger-ui.enabled: false
